# Generated by Django 4.1.1 on 2022-09-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="folders",
            new_name="folder",
        ),
    ]
